#################
# Elasticsearch deployed as StatefulSet
#################

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    component: elasticsearch-node
    role: master
  name: elasticsearch-master
  namespace: k8-elkstack
spec:
  selector:
    matchLabels:
      component: elasticsearch-node
      role: master # has to match .spec.template.metadata.labels
  serviceName: elasticsearch-discovery-svc
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        component: elasticsearch-node
        role: master # has to match .spec.selector.matchLabels
    spec:
      nodeSelector:
        elasticsearch-host: "true"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
      - name: elasticsearch-master
        image: kannasdocker/elkstack-xpo:elasticsearch-6.8.5
        securityContext:
          privileged: true
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            memory: 1Gi
            cpu: 1
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data/
          name: masterstorage
          mountPropagation: Bidirectional
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
          name: elasticsearch-yml
        - mountPath: /usr/share/elasticsearch/config/jvm.options
          subPath: jvm.options
          name: jvm-options
        - mountPath: /usr/share/elasticsearch/config/log4j2.properties
          subPath: log4j2.properties
          name: log4j2-properties
      restartPolicy: Always
      volumes:
      - configMap:
          name: elasticsearch-master-config
        name: elasticsearch-yml
      - configMap:
          name: elasticsearch-master-config
        name: jvm-options
      - configMap:
          name: elasticsearch-master-config
        name: log4j2-properties
      - name: masterstorage
        hostPath:
          path: /home/ec2-user/elasticsearch/master/data
          type: Directory
